server:
   port: 8001

spring:
  datasource:
    name:
    url: jdbc:mysql://127.0.0.1:3306/heima
    username: root
    password: jkkc20191216
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    #password: ~QEtu123321
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
