server:
   port: 8001

spring:
  datasource:
    name:
    url: jdbc:mysql://45.32.233.23:3306/test
    username: root
    password: newpassword
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
